### ISSUE TITLE
Text blinking with cursor

### ISSUE THREAD

**Issue by joonaspaakko** [Matthew-Smith/atom-glowing-cursor#9]
This is what is happening:
![2017-10-04 13 28 52](https://user-images.githubusercontent.com/1164476/31172161-2939e5ba-a90b-11e7-826a-5603bd0c91dd.gif)

All I really know is... disabling this package and restarting atom fixes the issue.

I was able to do a quick fix by adding this to stylesheet, without having to disable the package:

> Obviously it gets rid of the cursor animation, but at least my magenta color is not blinking anymore...

```less
atom-text-editor {
  .cursor {
    transition: none !important;
  }
}
```
